# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Complex Lab
description: >- # this means to ignore newlines until "baseurl:"
  Complex Lab's official website
baseurl: "" # the subpath of the site
url: "https://zhanweigao.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"
remote_theme: eliottvincent/bay

header:
  pages:
    - name: Home
      slug: /
    - name: Projects
      slug: /projects
    #- name: Blog
    #- name: CV
    #  slug: /CV
    - name: Publications
    - name: Presentations
    - name: Teaching
    - name: Science
    - name: News

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: Email
      link: mailto:anamatoso92@gmail.com
    - name: Address
      value: Beijing
      #link: mailto:Beijing

  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/anamatoso
    - name: GitHub
      link: http://github.com/anamatoso

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
